-- V1__create_reference_tables.sql
-- 모든 사건이 함께 쓰는 기준 데이터: 양형기준 버전, 사전 판단 형량 구간 (ERD 3-1)

-- 양형기준 버전 (사건별 적용 버전 기록용, REQ-080)
CREATE TABLE sentencing_guideline (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY,
    crime_category varchar(50)  NOT NULL,  -- 예: 사기범죄
    version_name   varchar(50)  NOT NULL,  -- 예: 2024 개정
    effective_date date         NOT NULL,  -- 시행일
    source_url     varchar(300),
    CONSTRAINT pk_sentencing_guideline PRIMARY KEY (id)
);

-- 사전 판단 형량 구간 (S-03 선택지, REQ-016)
CREATE TABLE sentence_range_option (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY,
    crime_type    varchar(20) NOT NULL,
    label         varchar(50) NOT NULL,
    kind          varchar(20) NOT NULL,
    min_months    int,                    -- 실형 구간 하한 (이상), NULL이면 제한 없음
    max_months    int,                    -- 실형 구간 상한 (미만), NULL이면 제한 없음
    display_order int         NOT NULL,
    CONSTRAINT pk_sentence_range_option PRIMARY KEY (id),
    CONSTRAINT chk_sentence_range_option_crime_type CHECK (crime_type IN ('MURDER', 'FRAUD', 'INJURY')),
    CONSTRAINT chk_sentence_range_option_kind
        CHECK (kind IN ('FINE', 'SUSPENDED', 'PRISON', 'LIFE_IMPRISONMENT', 'DEATH_PENALTY'))
);

-- 범죄 유형별 구간 조회용 (API 4)
CREATE INDEX idx_sentence_range_option_crime_type ON sentence_range_option (crime_type);

-- 형량 구간 (모든 환경에 같은 값이 있어야 하는 고정 데이터)
-- 공통 7개를 모든 범죄 유형에 넣고, 법정형에 무기징역 · 사형이 있는 살인에만 2개를 더한다 (살인 9개)
-- 사기를 먼저 넣어 ID가 1 ~ 7이 되도록 해 API 명세서 예시(rangeOptionId 1 ~ 7)와 맞춘다
INSERT INTO sentence_range_option (crime_type, label, kind, min_months, max_months, display_order)
SELECT s.crime_type, s.label, s.kind, s.min_months, s.max_months, s.display_order
FROM (
    -- 공통 구간 7개
    SELECT t.crime_type, t.type_order, o.label, o.kind, o.min_months, o.max_months, o.display_order
    FROM (VALUES ('FRAUD', 1), ('MURDER', 2), ('INJURY', 3)) AS t(crime_type, type_order)
    CROSS JOIN (VALUES
        ('벌금형',                     'FINE',      NULL::int, NULL::int, 1),
        ('징역형 집행유예',            'SUSPENDED', NULL,      NULL,      2),
        ('실형 3년 미만',              'PRISON',    NULL,      36,        3),
        ('실형 3년 이상 ~ 5년 미만',   'PRISON',    36,        60,        4),
        ('실형 5년 이상 ~ 10년 미만',  'PRISON',    60,        120,       5),
        ('실형 10년 이상 ~ 20년 미만', 'PRISON',    120,       240,       6),
        ('실형 20년 이상',             'PRISON',    240,       NULL,      7)
    ) AS o(label, kind, min_months, max_months, display_order)

    UNION ALL

    -- 살인 전용 구간 2개 (개월 범위 없음)
    SELECT 'MURDER', 2, e.label, e.kind, e.min_months, e.max_months, e.display_order
    FROM (VALUES
        ('무기징역', 'LIFE_IMPRISONMENT', NULL::int, NULL::int, 8),
        ('사형',     'DEATH_PENALTY',     NULL,      NULL,      9)
    ) AS e(label, kind, min_months, max_months, display_order)
) AS s
ORDER BY s.type_order, s.display_order;
