-- V2__create_case_content.sql
-- 사건마다 팀이 등록하는 콘텐츠: 사건, 사건 정보 섹션, 형벌 규칙, 판단 요소, 원본 판결문 (ERD 3-1)

-- 사건 (case는 SQL 예약어라 legal_case)
CREATE TABLE legal_case (
    id                     bigint       GENERATED BY DEFAULT AS IDENTITY,
    title                  varchar(100) NOT NULL,
    crime_type             varchar(20)  NOT NULL,
    charge_name            varchar(100) NOT NULL,  -- 죄명 (예: 사기)
    short_intro            varchar(200) NOT NULL,  -- 목록 카드용 짧은 소개
    keywords               jsonb,                  -- 목록 카드용 중립 키워드 배열
    difficulty             varchar(10),
    estimated_minutes      int,
    overview               text         NOT NULL,  -- S-03 사건 개요 (뉴스 수준, 중립 표현)
    thumbnail_url          varchar(300),           -- 없으면 화면이 범죄 유형별 기본 이미지 사용
    deidentified_items     jsonb,                  -- (확장) 비식별화한 항목 종류 배열
    applied_law            varchar(200) NOT NULL,  -- 적용 법조문 (고정 입력값)
    statutory_penalty_text varchar(200) NOT NULL,  -- 법정형 안내 문구
    recommended_min_months int,                    -- 권고 형량 하한 (개월)
    recommended_max_months int,                    -- 권고 형량 상한 (개월)
    recommended_basis      text,                   -- 권고 범위 산출 근거
    guideline_id           bigint,                 -- 적용 양형기준 버전
    incident_date          date,                   -- 사건 발생일 (양형기준 버전 판단 근거)
    status                 varchar(20)  NOT NULL,  -- PUBLISHED만 사용자에게 노출
    published_at           timestamptz,
    created_at             timestamptz  NOT NULL DEFAULT now(),
    updated_at             timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT pk_legal_case PRIMARY KEY (id),
    CONSTRAINT fk_legal_case_sentencing_guideline FOREIGN KEY (guideline_id) REFERENCES sentencing_guideline (id),
    CONSTRAINT chk_legal_case_crime_type CHECK (crime_type IN ('MURDER', 'FRAUD', 'INJURY')),
    CONSTRAINT chk_legal_case_difficulty CHECK (difficulty IN ('LOW', 'MID', 'HIGH')),
    CONSTRAINT chk_legal_case_status CHECK (status IN ('DRAFT', 'REVIEW', 'PUBLISHED'))
);

CREATE INDEX idx_legal_case_guideline_id ON legal_case (guideline_id);

-- 사건 정보 섹션 (S-04 · S-05). 섹션 ① 개요는 legal_case.overview를 쓰고 여기에 중복 저장하지 않는다
CREATE TABLE case_section (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY,
    case_id       bigint       NOT NULL,
    stage         varchar(20)  NOT NULL,
    section_type  varchar(30)  NOT NULL,  -- 범죄 유형마다 값이 늘어날 수 있어 CHECK를 두지 않음
    title         varchar(100),
    content       text,
    data          jsonb,                  -- 피해 결과 카드 값, 용어 설명 목록 등
    display_order int          NOT NULL,
    CONSTRAINT pk_case_section PRIMARY KEY (id),
    CONSTRAINT fk_case_section_legal_case FOREIGN KEY (case_id) REFERENCES legal_case (id),
    CONSTRAINT chk_case_section_stage CHECK (stage IN ('DETAIL', 'ARGUMENT', 'LAW', 'SUMMARY'))
);

CREATE INDEX idx_case_section_case_id ON case_section (case_id);

-- 형벌별 법정형과 선고 가능 범위 (S-06 선택지, 선고 가능 범위 밖 판결 거절 기준)
-- 징역은 개월, 벌금은 원 단위
CREATE TABLE penalty_rule (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY,
    case_id            bigint       NOT NULL,
    penalty_type       varchar(20)  NOT NULL,
    statutory_min      bigint,               -- 법정형 하한 (조문에 없으면 NULL)
    statutory_max      bigint,               -- 법정형 상한
    allowed_min        bigint,               -- 선고 가능 하한 (법률상 감경 + 작량감경 적용)
    allowed_max        bigint,               -- 선고 가능 상한
    allowed_basis      varchar(300),         -- 선고 가능 범위 산출 근거
    suspension_allowed boolean      NOT NULL,
    display_order      int          NOT NULL,
    CONSTRAINT pk_penalty_rule PRIMARY KEY (id),
    CONSTRAINT fk_penalty_rule_legal_case FOREIGN KEY (case_id) REFERENCES legal_case (id),
    -- 사건마다 형벌 종류별 규칙은 1개 (API 8 · 9가 형벌 종류로 규칙 하나를 찾는다)
    CONSTRAINT uk_penalty_rule_case_penalty_type UNIQUE (case_id, penalty_type),
    CONSTRAINT chk_penalty_rule_penalty_type
        CHECK (penalty_type IN ('PRISON', 'FINE', 'LIFE_IMPRISONMENT', 'DEATH_PENALTY')),
    -- 무기징역 · 사형은 형량 범위가 없고 집행유예를 적용할 수 없다 (ERD v1.4)
    CONSTRAINT chk_penalty_rule_life_death_no_range CHECK (
        penalty_type NOT IN ('LIFE_IMPRISONMENT', 'DEATH_PENALTY')
        OR (statutory_min IS NULL AND statutory_max IS NULL
            AND allowed_min IS NULL AND allowed_max IS NULL
            AND suspension_allowed = false)
    )
);

-- case_id는 유니크 제약의 첫 컬럼이라 별도 인덱스 생략

-- 사건별 판단 요소 목록 (사용자 · AI · 재판부 공통)
CREATE TABLE factor (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY,
    case_id       bigint       NOT NULL,
    label         varchar(100) NOT NULL,  -- 판단 요소 문구
    pre_label     varchar(100),           -- 사전 판단용 짧은 문구 (OVERVIEW 요소만)
    reveal_stage  varchar(20)  NOT NULL,  -- 사용자가 처음 알게 되는 단계
    summary_tag   varchar(20)  NOT NULL,  -- 요약 태그 (사건별로 팀이 붙여 CHECK를 두지 않음)
    display_order int          NOT NULL,
    CONSTRAINT pk_factor PRIMARY KEY (id),
    CONSTRAINT fk_factor_legal_case FOREIGN KEY (case_id) REFERENCES legal_case (id),
    CONSTRAINT chk_factor_reveal_stage CHECK (reveal_stage IN ('OVERVIEW', 'DETAIL', 'ARGUMENT', 'LAW'))
);

CREATE INDEX idx_factor_case_id ON factor (case_id);

-- 원본 판결문 (내부 전용, 사용자 응답에 절대 포함하지 않음)
CREATE TABLE case_source (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY,
    case_id       bigint      NOT NULL,
    court_level   varchar(20) NOT NULL,
    case_number   varchar(50) NOT NULL,
    court_name    varchar(50),
    decided_at    date,
    is_final      boolean     NOT NULL,  -- 최종 확정 판결 여부
    source_org    varchar(50) NOT NULL,  -- 출처 기관 (사용자에게 노출 가능한 유일한 컬럼)
    original_text text,
    note          text,
    CONSTRAINT pk_case_source PRIMARY KEY (id),
    CONSTRAINT fk_case_source_legal_case FOREIGN KEY (case_id) REFERENCES legal_case (id),
    CONSTRAINT chk_case_source_court_level CHECK (court_level IN ('FIRST', 'APPEAL', 'SUPREME'))
);

CREATE INDEX idx_case_source_case_id ON case_source (case_id);
