-- V3__create_experience.sql
-- 시스템이 기록하는 사용자 체험: 익명 사용자, 체험 (ERD 3-2)

-- 익명 사용자 (브라우저 쿠키 NLNB_AID의 값). id는 쿠키를 발급하는 서버 코드에서 생성한다
CREATE TABLE anonymous_user (
    id           uuid        NOT NULL,
    member_id    bigint,                          -- (이후) 로그인 시 연결할 회원. member 테이블이 없어 FK는 두지 않음
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_anonymous_user PRIMARY KEY (id)
);

-- 체험 (익명 사용자 × 사건 × 회차). 진행 상태는 앞으로만 이동한다 (IA 9장)
CREATE TABLE experience (
    id                   bigint      GENERATED BY DEFAULT AS IDENTITY,
    anonymous_user_id    uuid        NOT NULL,
    case_id              bigint      NOT NULL,
    attempt_no           int         NOT NULL DEFAULT 1,          -- MVP에서는 항상 1
    member_id            bigint,                                  -- (이후) 체험 시작 시 로그인 상태였다면 회원 ID
    status               varchar(30) NOT NULL DEFAULT 'STARTED',
    last_reviewed_step   int         NOT NULL DEFAULT 0,          -- S-04에서 확인을 마친 마지막 섹션 (0 ~ 4)
    started_at           timestamptz NOT NULL DEFAULT now(),
    pre_judged_at        timestamptz,
    reviewed_at          timestamptz,
    verdict_confirmed_at timestamptz,
    ai_revealed_at       timestamptz,
    completed_at         timestamptz,
    updated_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_experience PRIMARY KEY (id),
    CONSTRAINT fk_experience_anonymous_user FOREIGN KEY (anonymous_user_id) REFERENCES anonymous_user (id),
    CONSTRAINT fk_experience_legal_case FOREIGN KEY (case_id) REFERENCES legal_case (id),
    -- 같은 사용자가 같은 사건을 같은 회차로 두 번 시작할 수 없다 (동시 요청 방지)
    CONSTRAINT uk_experience_user_case_attempt UNIQUE (anonymous_user_id, case_id, attempt_no),
    CONSTRAINT chk_experience_status CHECK (status IN (
        'STARTED', 'PRE_JUDGED', 'REVIEWING', 'REVIEWED',
        'VERDICT_CONFIRMED', 'AI_REVEALED', 'COMPLETED')),
    CONSTRAINT chk_experience_last_reviewed_step CHECK (last_reviewed_step BETWEEN 0 AND 4),
    CONSTRAINT chk_experience_attempt_no CHECK (attempt_no >= 1)
);

-- anonymous_user_id는 유니크 제약의 첫 컬럼이라 별도 인덱스 생략
CREATE INDEX idx_experience_case_id ON experience (case_id);
