-- V4__create_judgment.sql
-- 판단 (사용자 사전 판단 · 최종 판결, AI 판결, 재판부 판결을 한 테이블에) (ERD 3-3)

CREATE TABLE judgment (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY,
    case_id            bigint       NOT NULL,
    subject_type       varchar(20)  NOT NULL,  -- 판단 주체 (이후 JURY 등 추가 가능)
    timing             varchar(10)  NOT NULL,  -- PRE는 사용자 사전 판단, FINAL은 최종 판결
    experience_id      bigint,                 -- USER일 때만
    range_option_id    bigint,                 -- PRE일 때만 (사전 판단 형량 구간)
    penalty_type       varchar(20),            -- FINAL일 때 필수
    prison_months      int,                    -- 징역 개월
    fine_amount        bigint,                 -- 벌금 (원)
    suspension_months  int,                    -- 집행유예 기간 (개월)
    extra_dispositions jsonb,                  -- 부가 처분 (주로 COURT)
    summary            varchar(100),           -- S-09 판결 카드 한 줄 요약 (AI · COURT, USER는 저장하지 않음)
    reasoning          text,                   -- 판결 이유 요약 (AI · COURT)
    plain_explanation  text,                   -- 쉬운 설명 (COURT)
    excerpt            text,                   -- 판결문 발췌 (COURT, 비식별화 적용)
    free_opinion       text,                   -- 자유 의견 (USER, 비교 대상 아님)
    reference_tags     jsonb,                  -- 참고 자료 태그 (AI)
    is_published       boolean      NOT NULL,  -- AI · COURT는 검수 후 true만 노출, USER는 항상 true
    created_at         timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT pk_judgment PRIMARY KEY (id),
    CONSTRAINT fk_judgment_legal_case FOREIGN KEY (case_id) REFERENCES legal_case (id),
    CONSTRAINT fk_judgment_experience FOREIGN KEY (experience_id) REFERENCES experience (id),
    CONSTRAINT fk_judgment_sentence_range_option FOREIGN KEY (range_option_id) REFERENCES sentence_range_option (id),

    -- 한 체험에 사전 판단 1개, 최종 판결 1개 (수정 · 재제출 불가). AI · COURT는 experience_id가 NULL이라 제외된다
    CONSTRAINT uk_judgment_experience_timing UNIQUE (experience_id, timing),

    CONSTRAINT chk_judgment_subject_type CHECK (subject_type IN ('USER', 'AI', 'COURT')),
    CONSTRAINT chk_judgment_timing CHECK (timing IN ('PRE', 'FINAL')),
    CONSTRAINT chk_judgment_penalty_type
        CHECK (penalty_type IN ('PRISON', 'FINE', 'LIFE_IMPRISONMENT', 'DEATH_PENALTY')),

    -- 사전 판단 형식: 사용자만, 형량 구간 필수, 형벌 값은 모두 비움
    CONSTRAINT chk_judgment_pre CHECK (
        timing <> 'PRE'
        OR (subject_type = 'USER' AND range_option_id IS NOT NULL
            AND penalty_type IS NULL AND prison_months IS NULL
            AND fine_amount IS NULL AND suspension_months IS NULL)
    ),
    -- 최종 판결 형식: 형벌 종류 필수, 형량 구간은 비움
    CONSTRAINT chk_judgment_final CHECK (
        timing <> 'FINAL' OR (penalty_type IS NOT NULL AND range_option_id IS NULL)
    ),
    -- 형벌 종류별 값: 징역은 개월, 벌금은 금액, 무기징역 · 사형은 개월 · 금액 · 집행유예 모두 없음
    CONSTRAINT chk_judgment_penalty_values CHECK (
        penalty_type IS NULL
        OR (penalty_type = 'PRISON' AND prison_months IS NOT NULL AND fine_amount IS NULL)
        OR (penalty_type = 'FINE' AND fine_amount IS NOT NULL AND prison_months IS NULL)
        OR (penalty_type IN ('LIFE_IMPRISONMENT', 'DEATH_PENALTY')
            AND prison_months IS NULL AND fine_amount IS NULL AND suspension_months IS NULL)
    ),
    -- 사용자 판단만 체험에 속한다
    CONSTRAINT chk_judgment_user_experience CHECK ((subject_type = 'USER') = (experience_id IS NOT NULL))
);

-- 사건마다 공개된 AI 판결 1개, 공개된 재판부 판결 1개 (모든 사용자에게 같은 판결, REQ-046)
CREATE UNIQUE INDEX uk_judgment_published
    ON judgment (case_id, subject_type)
    WHERE is_published = TRUE AND subject_type IN ('AI', 'COURT');

-- experience_id는 유니크 제약의 첫 컬럼이라 별도 인덱스 생략
CREATE INDEX idx_judgment_case_id ON judgment (case_id);
CREATE INDEX idx_judgment_range_option_id ON judgment (range_option_id);

-- 판단 요소 평가. 행이 없으면 "고려하지 않음"(—)으로 본다
CREATE TABLE judgment_factor (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY,
    judgment_id bigint      NOT NULL,
    factor_id   bigint      NOT NULL,
    direction   varchar(10),           -- 사전 판단(PRE)은 방향 없이 NULL
    evidence    text,                  -- 재판부 판단의 근거 문장 (COURT)
    CONSTRAINT pk_judgment_factor PRIMARY KEY (id),
    CONSTRAINT fk_judgment_factor_judgment FOREIGN KEY (judgment_id) REFERENCES judgment (id),
    CONSTRAINT fk_judgment_factor_factor FOREIGN KEY (factor_id) REFERENCES factor (id),
    CONSTRAINT uk_judgment_factor_judgment_factor UNIQUE (judgment_id, factor_id),
    CONSTRAINT chk_judgment_factor_direction CHECK (direction IN ('UP', 'DOWN'))
);

-- judgment_id는 유니크 제약의 첫 컬럼이라 별도 인덱스 생략
CREATE INDEX idx_judgment_factor_factor_id ON judgment_factor (factor_id);
