-- V5__create_extension_tables.sql
-- 확장 단계 테이블: AI 판결 생성 기록, 세 판결 비교 분석 (ERD 3-3)
-- MVP 기능은 이 테이블 없이 동작한다. 스키마를 ERD와 맞추기 위해 미리 만들어 둔다

-- AI 판결 생성 기록 (어떤 조건으로 만든 AI 판결인지, REQ-047 · 079)
-- 모델 · 프롬프트가 바뀌면 새 judgment와 새 행을 만들고 기존 행은 지우지 않는다
CREATE TABLE ai_generation (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY,
    judgment_id    bigint      NOT NULL,
    model_name     varchar(50) NOT NULL,
    prompt_version varchar(30) NOT NULL,
    input_snapshot jsonb,                 -- AI에 넣은 입력 (실제 판결이 없는지 검증용)
    raw_output     jsonb,                 -- 모델 원본 출력
    review_status  varchar(20) NOT NULL,
    reviewed_by    varchar(50),
    reviewed_at    timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_ai_generation PRIMARY KEY (id),
    CONSTRAINT fk_ai_generation_judgment FOREIGN KEY (judgment_id) REFERENCES judgment (id),
    CONSTRAINT uk_ai_generation_judgment UNIQUE (judgment_id),
    CONSTRAINT chk_ai_generation_review_status CHECK (review_status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- 세 판결 비교 분석 (체험별 실시간 생성, 체험당 1개, FR-6-3)
-- 실제 판결 공개(AI_REVEALED) 시 PENDING으로 만들고, 검증을 통과한 결과만 DONE으로 저장한다
CREATE TABLE comparison_analysis (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY,
    experience_id  bigint      NOT NULL,
    status         varchar(20) NOT NULL,
    content        jsonb,                 -- 검증을 통과한 분석 (항목마다 근거 요소 ID 포함)
    fail_reason    varchar(30),
    model_name     varchar(50) NOT NULL,
    prompt_version varchar(30) NOT NULL,
    input_snapshot jsonb,                 -- AI에 넣은 입력 (사건 원문 · 판결문 전문이 없는지 점검용)
    raw_output     jsonb,                 -- 모델 원본 출력 (실패 원인 분석 · 샘플 점검용)
    created_at     timestamptz NOT NULL DEFAULT now(),  -- 생성 시작 시각
    completed_at   timestamptz,                         -- DONE · FAILED가 된 시각
    CONSTRAINT pk_comparison_analysis PRIMARY KEY (id),
    CONSTRAINT fk_comparison_analysis_experience FOREIGN KEY (experience_id) REFERENCES experience (id),
    -- 동시 요청이 와도 체험당 한 번만 생성한다
    CONSTRAINT uk_comparison_analysis_experience UNIQUE (experience_id),
    CONSTRAINT chk_comparison_analysis_status CHECK (status IN ('PENDING', 'DONE', 'FAILED')),
    CONSTRAINT chk_comparison_analysis_fail_reason CHECK (fail_reason IN (
        'INVALID_FACTOR', 'FORBIDDEN_EXPRESSION', 'INVALID_FORMAT', 'TIMEOUT', 'API_ERROR'))
);
