-- V9__create_admin_account.sql
-- 관리자 계정 (확장 단계, BE-39). 관리자 후검수(BE-33) API는 이 계정으로 로그인한 관리자만 쓴다.
-- 사용자는 지금처럼 익명 ID 쿠키로만 구분하고 이 테이블과 관계없다.
-- password_hash는 BCrypt 해시. OAuth로만 로그인하는 관리자(BE-40)는 비밀번호가 없을 수 있어 NULL을 허용한다.
-- email은 소문자로 정규화해 저장하고 대소문자 구분 없이 하나만 허용한다.
CREATE TABLE admin_account (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY,
    email         varchar(254) NOT NULL,
    password_hash varchar(100),
    display_name  varchar(50)  NOT NULL,
    enabled       boolean      NOT NULL DEFAULT true,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    last_login_at timestamptz,
    CONSTRAINT pk_admin_account PRIMARY KEY (id),
    CONSTRAINT uk_admin_account_email UNIQUE (email),
    CONSTRAINT chk_admin_account_email_lower CHECK (email = lower(email))
);
